// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v4.25.3
// source: siauth_schema.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export interface ProtoUser {
  username: string;
  passwordHash: Uint8Array;
  name?: string | undefined;
  email?: string | undefined;
  number?: string | undefined;
}

export interface Token {
  code: string;
  username: string;
  expiry: number;
}

export interface AuthCode {
  code: string;
  username: string;
  clientId: string;
  redirectUri: string;
  /** for PKCE (S256) */
  codeChallenge?: string | undefined;
  expiry: number;
  used: boolean;
}

export interface ProtoOIDCUserMapping {
  providerName: string;
  providerSub: string;
  username: string;
  createdAt: number;
}

export interface StatusParams {
}

export interface StatusResult {
  username: string;
  isAuthenticated: boolean;
  isSubscribed: boolean;
}

export interface SignupParams {
  username: string;
  password: string;
  name?: string | undefined;
  email?: string | undefined;
  number?: string | undefined;
}

export interface SignupResult {
  success: boolean;
  username: string;
}

export interface LoginParams {
  username: string;
  password: string;
}

export interface LoginResult {
  success: boolean;
}

export interface LogoutParams {
}

export interface LogoutResult {
  success: boolean;
}

export interface ChangePasswordParams {
  username: string;
  oldPassword: string;
  newPassword: string;
}

export interface ChangePasswordResult {
  success: boolean;
}

export interface ResetPasswordParams {
  username: string;
  newPassword: string;
  resetToken: string;
}

export interface ResetPasswordResult {
  success: boolean;
}

export interface RequestAuthCodeParams {
  clientId: string;
  redirectUri: string;
  /** for PKCE (S256) */
  codeChallenge?: string | undefined;
}

export interface RequestAuthCodeResult {
  success: boolean;
  authCode?: string | undefined;
}

export interface ExchangeAuthCodeParams {
  clientId: string;
  redirectUri: string;
  authCode: string;
  /** for PKCE (S256) */
  codeVerifier?: string | undefined;
}

export interface ExchangeAuthCodeResult {
  success: boolean;
  token?: Token | undefined;
}

export interface GetOIDCAuthURLParams {
  providerName: string;
  state?:
    | string
    | undefined;
  /** PKCE */
  codeChallenge?: string | undefined;
}

export interface GetOIDCAuthURLResult {
  success: boolean;
  authUrl?: string | undefined;
}

export interface OIDCLoginParams {
  providerName: string;
  code: string;
  /** PKCE */
  codeVerifier?: string | undefined;
}

export interface OIDCLoginResult {
  success: boolean;
  token?: Token | undefined;
  username?: string | undefined;
}

function createBaseProtoUser(): ProtoUser {
  return { username: "", passwordHash: new Uint8Array(0), name: undefined, email: undefined, number: undefined };
}

export const ProtoUser: MessageFns<ProtoUser> = {
  encode(message: ProtoUser, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.username !== "") {
      writer.uint32(10).string(message.username);
    }
    if (message.passwordHash.length !== 0) {
      writer.uint32(18).bytes(message.passwordHash);
    }
    if (message.name !== undefined) {
      writer.uint32(26).string(message.name);
    }
    if (message.email !== undefined) {
      writer.uint32(34).string(message.email);
    }
    if (message.number !== undefined) {
      writer.uint32(42).string(message.number);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProtoUser {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProtoUser();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.passwordHash = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.number = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProtoUser {
    return {
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      passwordHash: isSet(object.passwordHash) ? bytesFromBase64(object.passwordHash) : new Uint8Array(0),
      name: isSet(object.name) ? globalThis.String(object.name) : undefined,
      email: isSet(object.email) ? globalThis.String(object.email) : undefined,
      number: isSet(object.number) ? globalThis.String(object.number) : undefined,
    };
  },

  toJSON(message: ProtoUser): unknown {
    const obj: any = {};
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.passwordHash.length !== 0) {
      obj.passwordHash = base64FromBytes(message.passwordHash);
    }
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    if (message.email !== undefined) {
      obj.email = message.email;
    }
    if (message.number !== undefined) {
      obj.number = message.number;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProtoUser>, I>>(base?: I): ProtoUser {
    return ProtoUser.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProtoUser>, I>>(object: I): ProtoUser {
    const message = createBaseProtoUser();
    message.username = object.username ?? "";
    message.passwordHash = object.passwordHash ?? new Uint8Array(0);
    message.name = object.name ?? undefined;
    message.email = object.email ?? undefined;
    message.number = object.number ?? undefined;
    return message;
  },
};

function createBaseToken(): Token {
  return { code: "", username: "", expiry: 0 };
}

export const Token: MessageFns<Token> = {
  encode(message: Token, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== "") {
      writer.uint32(10).string(message.code);
    }
    if (message.username !== "") {
      writer.uint32(18).string(message.username);
    }
    if (message.expiry !== 0) {
      writer.uint32(24).int64(message.expiry);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Token {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseToken();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.code = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.expiry = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Token {
    return {
      code: isSet(object.code) ? globalThis.String(object.code) : "",
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      expiry: isSet(object.expiry) ? globalThis.Number(object.expiry) : 0,
    };
  },

  toJSON(message: Token): unknown {
    const obj: any = {};
    if (message.code !== "") {
      obj.code = message.code;
    }
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.expiry !== 0) {
      obj.expiry = Math.round(message.expiry);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Token>, I>>(base?: I): Token {
    return Token.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Token>, I>>(object: I): Token {
    const message = createBaseToken();
    message.code = object.code ?? "";
    message.username = object.username ?? "";
    message.expiry = object.expiry ?? 0;
    return message;
  },
};

function createBaseAuthCode(): AuthCode {
  return { code: "", username: "", clientId: "", redirectUri: "", codeChallenge: undefined, expiry: 0, used: false };
}

export const AuthCode: MessageFns<AuthCode> = {
  encode(message: AuthCode, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.code !== "") {
      writer.uint32(10).string(message.code);
    }
    if (message.username !== "") {
      writer.uint32(18).string(message.username);
    }
    if (message.clientId !== "") {
      writer.uint32(26).string(message.clientId);
    }
    if (message.redirectUri !== "") {
      writer.uint32(34).string(message.redirectUri);
    }
    if (message.codeChallenge !== undefined) {
      writer.uint32(42).string(message.codeChallenge);
    }
    if (message.expiry !== 0) {
      writer.uint32(48).int64(message.expiry);
    }
    if (message.used !== false) {
      writer.uint32(56).bool(message.used);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuthCode {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthCode();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.code = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.clientId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.redirectUri = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.codeChallenge = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.expiry = longToNumber(reader.int64());
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.used = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AuthCode {
    return {
      code: isSet(object.code) ? globalThis.String(object.code) : "",
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      clientId: isSet(object.clientId) ? globalThis.String(object.clientId) : "",
      redirectUri: isSet(object.redirectUri) ? globalThis.String(object.redirectUri) : "",
      codeChallenge: isSet(object.codeChallenge) ? globalThis.String(object.codeChallenge) : undefined,
      expiry: isSet(object.expiry) ? globalThis.Number(object.expiry) : 0,
      used: isSet(object.used) ? globalThis.Boolean(object.used) : false,
    };
  },

  toJSON(message: AuthCode): unknown {
    const obj: any = {};
    if (message.code !== "") {
      obj.code = message.code;
    }
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.clientId !== "") {
      obj.clientId = message.clientId;
    }
    if (message.redirectUri !== "") {
      obj.redirectUri = message.redirectUri;
    }
    if (message.codeChallenge !== undefined) {
      obj.codeChallenge = message.codeChallenge;
    }
    if (message.expiry !== 0) {
      obj.expiry = Math.round(message.expiry);
    }
    if (message.used !== false) {
      obj.used = message.used;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AuthCode>, I>>(base?: I): AuthCode {
    return AuthCode.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AuthCode>, I>>(object: I): AuthCode {
    const message = createBaseAuthCode();
    message.code = object.code ?? "";
    message.username = object.username ?? "";
    message.clientId = object.clientId ?? "";
    message.redirectUri = object.redirectUri ?? "";
    message.codeChallenge = object.codeChallenge ?? undefined;
    message.expiry = object.expiry ?? 0;
    message.used = object.used ?? false;
    return message;
  },
};

function createBaseProtoOIDCUserMapping(): ProtoOIDCUserMapping {
  return { providerName: "", providerSub: "", username: "", createdAt: 0 };
}

export const ProtoOIDCUserMapping: MessageFns<ProtoOIDCUserMapping> = {
  encode(message: ProtoOIDCUserMapping, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.providerName !== "") {
      writer.uint32(10).string(message.providerName);
    }
    if (message.providerSub !== "") {
      writer.uint32(18).string(message.providerSub);
    }
    if (message.username !== "") {
      writer.uint32(26).string(message.username);
    }
    if (message.createdAt !== 0) {
      writer.uint32(32).int64(message.createdAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ProtoOIDCUserMapping {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseProtoOIDCUserMapping();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.providerName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.providerSub = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.createdAt = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ProtoOIDCUserMapping {
    return {
      providerName: isSet(object.providerName) ? globalThis.String(object.providerName) : "",
      providerSub: isSet(object.providerSub) ? globalThis.String(object.providerSub) : "",
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      createdAt: isSet(object.createdAt) ? globalThis.Number(object.createdAt) : 0,
    };
  },

  toJSON(message: ProtoOIDCUserMapping): unknown {
    const obj: any = {};
    if (message.providerName !== "") {
      obj.providerName = message.providerName;
    }
    if (message.providerSub !== "") {
      obj.providerSub = message.providerSub;
    }
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.createdAt !== 0) {
      obj.createdAt = Math.round(message.createdAt);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ProtoOIDCUserMapping>, I>>(base?: I): ProtoOIDCUserMapping {
    return ProtoOIDCUserMapping.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ProtoOIDCUserMapping>, I>>(object: I): ProtoOIDCUserMapping {
    const message = createBaseProtoOIDCUserMapping();
    message.providerName = object.providerName ?? "";
    message.providerSub = object.providerSub ?? "";
    message.username = object.username ?? "";
    message.createdAt = object.createdAt ?? 0;
    return message;
  },
};

function createBaseStatusParams(): StatusParams {
  return {};
}

export const StatusParams: MessageFns<StatusParams> = {
  encode(_: StatusParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StatusParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStatusParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): StatusParams {
    return {};
  },

  toJSON(_: StatusParams): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<StatusParams>, I>>(base?: I): StatusParams {
    return StatusParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StatusParams>, I>>(_: I): StatusParams {
    const message = createBaseStatusParams();
    return message;
  },
};

function createBaseStatusResult(): StatusResult {
  return { username: "", isAuthenticated: false, isSubscribed: false };
}

export const StatusResult: MessageFns<StatusResult> = {
  encode(message: StatusResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.username !== "") {
      writer.uint32(10).string(message.username);
    }
    if (message.isAuthenticated !== false) {
      writer.uint32(16).bool(message.isAuthenticated);
    }
    if (message.isSubscribed !== false) {
      writer.uint32(24).bool(message.isSubscribed);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StatusResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStatusResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.isAuthenticated = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.isSubscribed = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StatusResult {
    return {
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      isAuthenticated: isSet(object.isAuthenticated) ? globalThis.Boolean(object.isAuthenticated) : false,
      isSubscribed: isSet(object.isSubscribed) ? globalThis.Boolean(object.isSubscribed) : false,
    };
  },

  toJSON(message: StatusResult): unknown {
    const obj: any = {};
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.isAuthenticated !== false) {
      obj.isAuthenticated = message.isAuthenticated;
    }
    if (message.isSubscribed !== false) {
      obj.isSubscribed = message.isSubscribed;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StatusResult>, I>>(base?: I): StatusResult {
    return StatusResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StatusResult>, I>>(object: I): StatusResult {
    const message = createBaseStatusResult();
    message.username = object.username ?? "";
    message.isAuthenticated = object.isAuthenticated ?? false;
    message.isSubscribed = object.isSubscribed ?? false;
    return message;
  },
};

function createBaseSignupParams(): SignupParams {
  return { username: "", password: "", name: undefined, email: undefined, number: undefined };
}

export const SignupParams: MessageFns<SignupParams> = {
  encode(message: SignupParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.username !== "") {
      writer.uint32(10).string(message.username);
    }
    if (message.password !== "") {
      writer.uint32(18).string(message.password);
    }
    if (message.name !== undefined) {
      writer.uint32(26).string(message.name);
    }
    if (message.email !== undefined) {
      writer.uint32(34).string(message.email);
    }
    if (message.number !== undefined) {
      writer.uint32(42).string(message.number);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SignupParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSignupParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.number = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SignupParams {
    return {
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      password: isSet(object.password) ? globalThis.String(object.password) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : undefined,
      email: isSet(object.email) ? globalThis.String(object.email) : undefined,
      number: isSet(object.number) ? globalThis.String(object.number) : undefined,
    };
  },

  toJSON(message: SignupParams): unknown {
    const obj: any = {};
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.password !== "") {
      obj.password = message.password;
    }
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    if (message.email !== undefined) {
      obj.email = message.email;
    }
    if (message.number !== undefined) {
      obj.number = message.number;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SignupParams>, I>>(base?: I): SignupParams {
    return SignupParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SignupParams>, I>>(object: I): SignupParams {
    const message = createBaseSignupParams();
    message.username = object.username ?? "";
    message.password = object.password ?? "";
    message.name = object.name ?? undefined;
    message.email = object.email ?? undefined;
    message.number = object.number ?? undefined;
    return message;
  },
};

function createBaseSignupResult(): SignupResult {
  return { success: false, username: "" };
}

export const SignupResult: MessageFns<SignupResult> = {
  encode(message: SignupResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.username !== "") {
      writer.uint32(18).string(message.username);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SignupResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSignupResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.username = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SignupResult {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      username: isSet(object.username) ? globalThis.String(object.username) : "",
    };
  },

  toJSON(message: SignupResult): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.username !== "") {
      obj.username = message.username;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SignupResult>, I>>(base?: I): SignupResult {
    return SignupResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SignupResult>, I>>(object: I): SignupResult {
    const message = createBaseSignupResult();
    message.success = object.success ?? false;
    message.username = object.username ?? "";
    return message;
  },
};

function createBaseLoginParams(): LoginParams {
  return { username: "", password: "" };
}

export const LoginParams: MessageFns<LoginParams> = {
  encode(message: LoginParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.username !== "") {
      writer.uint32(10).string(message.username);
    }
    if (message.password !== "") {
      writer.uint32(18).string(message.password);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoginParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoginParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoginParams {
    return {
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      password: isSet(object.password) ? globalThis.String(object.password) : "",
    };
  },

  toJSON(message: LoginParams): unknown {
    const obj: any = {};
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.password !== "") {
      obj.password = message.password;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoginParams>, I>>(base?: I): LoginParams {
    return LoginParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoginParams>, I>>(object: I): LoginParams {
    const message = createBaseLoginParams();
    message.username = object.username ?? "";
    message.password = object.password ?? "";
    return message;
  },
};

function createBaseLoginResult(): LoginResult {
  return { success: false };
}

export const LoginResult: MessageFns<LoginResult> = {
  encode(message: LoginResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LoginResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLoginResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LoginResult {
    return { success: isSet(object.success) ? globalThis.Boolean(object.success) : false };
  },

  toJSON(message: LoginResult): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LoginResult>, I>>(base?: I): LoginResult {
    return LoginResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LoginResult>, I>>(object: I): LoginResult {
    const message = createBaseLoginResult();
    message.success = object.success ?? false;
    return message;
  },
};

function createBaseLogoutParams(): LogoutParams {
  return {};
}

export const LogoutParams: MessageFns<LogoutParams> = {
  encode(_: LogoutParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogoutParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogoutParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): LogoutParams {
    return {};
  },

  toJSON(_: LogoutParams): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<LogoutParams>, I>>(base?: I): LogoutParams {
    return LogoutParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogoutParams>, I>>(_: I): LogoutParams {
    const message = createBaseLogoutParams();
    return message;
  },
};

function createBaseLogoutResult(): LogoutResult {
  return { success: false };
}

export const LogoutResult: MessageFns<LogoutResult> = {
  encode(message: LogoutResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogoutResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogoutResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogoutResult {
    return { success: isSet(object.success) ? globalThis.Boolean(object.success) : false };
  },

  toJSON(message: LogoutResult): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogoutResult>, I>>(base?: I): LogoutResult {
    return LogoutResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogoutResult>, I>>(object: I): LogoutResult {
    const message = createBaseLogoutResult();
    message.success = object.success ?? false;
    return message;
  },
};

function createBaseChangePasswordParams(): ChangePasswordParams {
  return { username: "", oldPassword: "", newPassword: "" };
}

export const ChangePasswordParams: MessageFns<ChangePasswordParams> = {
  encode(message: ChangePasswordParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.username !== "") {
      writer.uint32(10).string(message.username);
    }
    if (message.oldPassword !== "") {
      writer.uint32(18).string(message.oldPassword);
    }
    if (message.newPassword !== "") {
      writer.uint32(26).string(message.newPassword);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChangePasswordParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChangePasswordParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.oldPassword = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.newPassword = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChangePasswordParams {
    return {
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      oldPassword: isSet(object.oldPassword) ? globalThis.String(object.oldPassword) : "",
      newPassword: isSet(object.newPassword) ? globalThis.String(object.newPassword) : "",
    };
  },

  toJSON(message: ChangePasswordParams): unknown {
    const obj: any = {};
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.oldPassword !== "") {
      obj.oldPassword = message.oldPassword;
    }
    if (message.newPassword !== "") {
      obj.newPassword = message.newPassword;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChangePasswordParams>, I>>(base?: I): ChangePasswordParams {
    return ChangePasswordParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChangePasswordParams>, I>>(object: I): ChangePasswordParams {
    const message = createBaseChangePasswordParams();
    message.username = object.username ?? "";
    message.oldPassword = object.oldPassword ?? "";
    message.newPassword = object.newPassword ?? "";
    return message;
  },
};

function createBaseChangePasswordResult(): ChangePasswordResult {
  return { success: false };
}

export const ChangePasswordResult: MessageFns<ChangePasswordResult> = {
  encode(message: ChangePasswordResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChangePasswordResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChangePasswordResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChangePasswordResult {
    return { success: isSet(object.success) ? globalThis.Boolean(object.success) : false };
  },

  toJSON(message: ChangePasswordResult): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChangePasswordResult>, I>>(base?: I): ChangePasswordResult {
    return ChangePasswordResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChangePasswordResult>, I>>(object: I): ChangePasswordResult {
    const message = createBaseChangePasswordResult();
    message.success = object.success ?? false;
    return message;
  },
};

function createBaseResetPasswordParams(): ResetPasswordParams {
  return { username: "", newPassword: "", resetToken: "" };
}

export const ResetPasswordParams: MessageFns<ResetPasswordParams> = {
  encode(message: ResetPasswordParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.username !== "") {
      writer.uint32(10).string(message.username);
    }
    if (message.newPassword !== "") {
      writer.uint32(18).string(message.newPassword);
    }
    if (message.resetToken !== "") {
      writer.uint32(26).string(message.resetToken);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResetPasswordParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResetPasswordParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.newPassword = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.resetToken = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ResetPasswordParams {
    return {
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      newPassword: isSet(object.newPassword) ? globalThis.String(object.newPassword) : "",
      resetToken: isSet(object.resetToken) ? globalThis.String(object.resetToken) : "",
    };
  },

  toJSON(message: ResetPasswordParams): unknown {
    const obj: any = {};
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.newPassword !== "") {
      obj.newPassword = message.newPassword;
    }
    if (message.resetToken !== "") {
      obj.resetToken = message.resetToken;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ResetPasswordParams>, I>>(base?: I): ResetPasswordParams {
    return ResetPasswordParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ResetPasswordParams>, I>>(object: I): ResetPasswordParams {
    const message = createBaseResetPasswordParams();
    message.username = object.username ?? "";
    message.newPassword = object.newPassword ?? "";
    message.resetToken = object.resetToken ?? "";
    return message;
  },
};

function createBaseResetPasswordResult(): ResetPasswordResult {
  return { success: false };
}

export const ResetPasswordResult: MessageFns<ResetPasswordResult> = {
  encode(message: ResetPasswordResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ResetPasswordResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseResetPasswordResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ResetPasswordResult {
    return { success: isSet(object.success) ? globalThis.Boolean(object.success) : false };
  },

  toJSON(message: ResetPasswordResult): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ResetPasswordResult>, I>>(base?: I): ResetPasswordResult {
    return ResetPasswordResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ResetPasswordResult>, I>>(object: I): ResetPasswordResult {
    const message = createBaseResetPasswordResult();
    message.success = object.success ?? false;
    return message;
  },
};

function createBaseRequestAuthCodeParams(): RequestAuthCodeParams {
  return { clientId: "", redirectUri: "", codeChallenge: undefined };
}

export const RequestAuthCodeParams: MessageFns<RequestAuthCodeParams> = {
  encode(message: RequestAuthCodeParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clientId !== "") {
      writer.uint32(10).string(message.clientId);
    }
    if (message.redirectUri !== "") {
      writer.uint32(18).string(message.redirectUri);
    }
    if (message.codeChallenge !== undefined) {
      writer.uint32(26).string(message.codeChallenge);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RequestAuthCodeParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequestAuthCodeParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clientId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.redirectUri = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.codeChallenge = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RequestAuthCodeParams {
    return {
      clientId: isSet(object.clientId) ? globalThis.String(object.clientId) : "",
      redirectUri: isSet(object.redirectUri) ? globalThis.String(object.redirectUri) : "",
      codeChallenge: isSet(object.codeChallenge) ? globalThis.String(object.codeChallenge) : undefined,
    };
  },

  toJSON(message: RequestAuthCodeParams): unknown {
    const obj: any = {};
    if (message.clientId !== "") {
      obj.clientId = message.clientId;
    }
    if (message.redirectUri !== "") {
      obj.redirectUri = message.redirectUri;
    }
    if (message.codeChallenge !== undefined) {
      obj.codeChallenge = message.codeChallenge;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RequestAuthCodeParams>, I>>(base?: I): RequestAuthCodeParams {
    return RequestAuthCodeParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RequestAuthCodeParams>, I>>(object: I): RequestAuthCodeParams {
    const message = createBaseRequestAuthCodeParams();
    message.clientId = object.clientId ?? "";
    message.redirectUri = object.redirectUri ?? "";
    message.codeChallenge = object.codeChallenge ?? undefined;
    return message;
  },
};

function createBaseRequestAuthCodeResult(): RequestAuthCodeResult {
  return { success: false, authCode: undefined };
}

export const RequestAuthCodeResult: MessageFns<RequestAuthCodeResult> = {
  encode(message: RequestAuthCodeResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.authCode !== undefined) {
      writer.uint32(18).string(message.authCode);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RequestAuthCodeResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequestAuthCodeResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.authCode = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RequestAuthCodeResult {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      authCode: isSet(object.authCode) ? globalThis.String(object.authCode) : undefined,
    };
  },

  toJSON(message: RequestAuthCodeResult): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.authCode !== undefined) {
      obj.authCode = message.authCode;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RequestAuthCodeResult>, I>>(base?: I): RequestAuthCodeResult {
    return RequestAuthCodeResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RequestAuthCodeResult>, I>>(object: I): RequestAuthCodeResult {
    const message = createBaseRequestAuthCodeResult();
    message.success = object.success ?? false;
    message.authCode = object.authCode ?? undefined;
    return message;
  },
};

function createBaseExchangeAuthCodeParams(): ExchangeAuthCodeParams {
  return { clientId: "", redirectUri: "", authCode: "", codeVerifier: undefined };
}

export const ExchangeAuthCodeParams: MessageFns<ExchangeAuthCodeParams> = {
  encode(message: ExchangeAuthCodeParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.clientId !== "") {
      writer.uint32(10).string(message.clientId);
    }
    if (message.redirectUri !== "") {
      writer.uint32(18).string(message.redirectUri);
    }
    if (message.authCode !== "") {
      writer.uint32(26).string(message.authCode);
    }
    if (message.codeVerifier !== undefined) {
      writer.uint32(34).string(message.codeVerifier);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExchangeAuthCodeParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExchangeAuthCodeParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.clientId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.redirectUri = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.authCode = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.codeVerifier = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExchangeAuthCodeParams {
    return {
      clientId: isSet(object.clientId) ? globalThis.String(object.clientId) : "",
      redirectUri: isSet(object.redirectUri) ? globalThis.String(object.redirectUri) : "",
      authCode: isSet(object.authCode) ? globalThis.String(object.authCode) : "",
      codeVerifier: isSet(object.codeVerifier) ? globalThis.String(object.codeVerifier) : undefined,
    };
  },

  toJSON(message: ExchangeAuthCodeParams): unknown {
    const obj: any = {};
    if (message.clientId !== "") {
      obj.clientId = message.clientId;
    }
    if (message.redirectUri !== "") {
      obj.redirectUri = message.redirectUri;
    }
    if (message.authCode !== "") {
      obj.authCode = message.authCode;
    }
    if (message.codeVerifier !== undefined) {
      obj.codeVerifier = message.codeVerifier;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExchangeAuthCodeParams>, I>>(base?: I): ExchangeAuthCodeParams {
    return ExchangeAuthCodeParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExchangeAuthCodeParams>, I>>(object: I): ExchangeAuthCodeParams {
    const message = createBaseExchangeAuthCodeParams();
    message.clientId = object.clientId ?? "";
    message.redirectUri = object.redirectUri ?? "";
    message.authCode = object.authCode ?? "";
    message.codeVerifier = object.codeVerifier ?? undefined;
    return message;
  },
};

function createBaseExchangeAuthCodeResult(): ExchangeAuthCodeResult {
  return { success: false, token: undefined };
}

export const ExchangeAuthCodeResult: MessageFns<ExchangeAuthCodeResult> = {
  encode(message: ExchangeAuthCodeResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.token !== undefined) {
      Token.encode(message.token, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExchangeAuthCodeResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExchangeAuthCodeResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.token = Token.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExchangeAuthCodeResult {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      token: isSet(object.token) ? Token.fromJSON(object.token) : undefined,
    };
  },

  toJSON(message: ExchangeAuthCodeResult): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.token !== undefined) {
      obj.token = Token.toJSON(message.token);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExchangeAuthCodeResult>, I>>(base?: I): ExchangeAuthCodeResult {
    return ExchangeAuthCodeResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExchangeAuthCodeResult>, I>>(object: I): ExchangeAuthCodeResult {
    const message = createBaseExchangeAuthCodeResult();
    message.success = object.success ?? false;
    message.token = (object.token !== undefined && object.token !== null) ? Token.fromPartial(object.token) : undefined;
    return message;
  },
};

function createBaseGetOIDCAuthURLParams(): GetOIDCAuthURLParams {
  return { providerName: "", state: undefined, codeChallenge: undefined };
}

export const GetOIDCAuthURLParams: MessageFns<GetOIDCAuthURLParams> = {
  encode(message: GetOIDCAuthURLParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.providerName !== "") {
      writer.uint32(10).string(message.providerName);
    }
    if (message.state !== undefined) {
      writer.uint32(18).string(message.state);
    }
    if (message.codeChallenge !== undefined) {
      writer.uint32(26).string(message.codeChallenge);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetOIDCAuthURLParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetOIDCAuthURLParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.providerName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.state = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.codeChallenge = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetOIDCAuthURLParams {
    return {
      providerName: isSet(object.providerName) ? globalThis.String(object.providerName) : "",
      state: isSet(object.state) ? globalThis.String(object.state) : undefined,
      codeChallenge: isSet(object.codeChallenge) ? globalThis.String(object.codeChallenge) : undefined,
    };
  },

  toJSON(message: GetOIDCAuthURLParams): unknown {
    const obj: any = {};
    if (message.providerName !== "") {
      obj.providerName = message.providerName;
    }
    if (message.state !== undefined) {
      obj.state = message.state;
    }
    if (message.codeChallenge !== undefined) {
      obj.codeChallenge = message.codeChallenge;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetOIDCAuthURLParams>, I>>(base?: I): GetOIDCAuthURLParams {
    return GetOIDCAuthURLParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetOIDCAuthURLParams>, I>>(object: I): GetOIDCAuthURLParams {
    const message = createBaseGetOIDCAuthURLParams();
    message.providerName = object.providerName ?? "";
    message.state = object.state ?? undefined;
    message.codeChallenge = object.codeChallenge ?? undefined;
    return message;
  },
};

function createBaseGetOIDCAuthURLResult(): GetOIDCAuthURLResult {
  return { success: false, authUrl: undefined };
}

export const GetOIDCAuthURLResult: MessageFns<GetOIDCAuthURLResult> = {
  encode(message: GetOIDCAuthURLResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.authUrl !== undefined) {
      writer.uint32(18).string(message.authUrl);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetOIDCAuthURLResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetOIDCAuthURLResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.authUrl = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetOIDCAuthURLResult {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      authUrl: isSet(object.authUrl) ? globalThis.String(object.authUrl) : undefined,
    };
  },

  toJSON(message: GetOIDCAuthURLResult): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.authUrl !== undefined) {
      obj.authUrl = message.authUrl;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetOIDCAuthURLResult>, I>>(base?: I): GetOIDCAuthURLResult {
    return GetOIDCAuthURLResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetOIDCAuthURLResult>, I>>(object: I): GetOIDCAuthURLResult {
    const message = createBaseGetOIDCAuthURLResult();
    message.success = object.success ?? false;
    message.authUrl = object.authUrl ?? undefined;
    return message;
  },
};

function createBaseOIDCLoginParams(): OIDCLoginParams {
  return { providerName: "", code: "", codeVerifier: undefined };
}

export const OIDCLoginParams: MessageFns<OIDCLoginParams> = {
  encode(message: OIDCLoginParams, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.providerName !== "") {
      writer.uint32(10).string(message.providerName);
    }
    if (message.code !== "") {
      writer.uint32(18).string(message.code);
    }
    if (message.codeVerifier !== undefined) {
      writer.uint32(26).string(message.codeVerifier);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OIDCLoginParams {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOIDCLoginParams();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.providerName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.code = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.codeVerifier = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OIDCLoginParams {
    return {
      providerName: isSet(object.providerName) ? globalThis.String(object.providerName) : "",
      code: isSet(object.code) ? globalThis.String(object.code) : "",
      codeVerifier: isSet(object.codeVerifier) ? globalThis.String(object.codeVerifier) : undefined,
    };
  },

  toJSON(message: OIDCLoginParams): unknown {
    const obj: any = {};
    if (message.providerName !== "") {
      obj.providerName = message.providerName;
    }
    if (message.code !== "") {
      obj.code = message.code;
    }
    if (message.codeVerifier !== undefined) {
      obj.codeVerifier = message.codeVerifier;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OIDCLoginParams>, I>>(base?: I): OIDCLoginParams {
    return OIDCLoginParams.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OIDCLoginParams>, I>>(object: I): OIDCLoginParams {
    const message = createBaseOIDCLoginParams();
    message.providerName = object.providerName ?? "";
    message.code = object.code ?? "";
    message.codeVerifier = object.codeVerifier ?? undefined;
    return message;
  },
};

function createBaseOIDCLoginResult(): OIDCLoginResult {
  return { success: false, token: undefined, username: undefined };
}

export const OIDCLoginResult: MessageFns<OIDCLoginResult> = {
  encode(message: OIDCLoginResult, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    if (message.token !== undefined) {
      Token.encode(message.token, writer.uint32(18).fork()).join();
    }
    if (message.username !== undefined) {
      writer.uint32(26).string(message.username);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OIDCLoginResult {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOIDCLoginResult();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.token = Token.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.username = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OIDCLoginResult {
    return {
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
      token: isSet(object.token) ? Token.fromJSON(object.token) : undefined,
      username: isSet(object.username) ? globalThis.String(object.username) : undefined,
    };
  },

  toJSON(message: OIDCLoginResult): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    if (message.token !== undefined) {
      obj.token = Token.toJSON(message.token);
    }
    if (message.username !== undefined) {
      obj.username = message.username;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OIDCLoginResult>, I>>(base?: I): OIDCLoginResult {
    return OIDCLoginResult.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OIDCLoginResult>, I>>(object: I): OIDCLoginResult {
    const message = createBaseOIDCLoginResult();
    message.success = object.success ?? false;
    message.token = (object.token !== undefined && object.token !== null) ? Token.fromPartial(object.token) : undefined;
    message.username = object.username ?? undefined;
    return message;
  },
};

export interface Auth {
  Status(request: StatusParams): Promise<StatusResult>;
  Signup(request: SignupParams): Promise<SignupResult>;
  Login(request: LoginParams): Promise<LoginResult>;
  Logout(request: LogoutParams): Promise<LogoutResult>;
  ChangePassword(request: ChangePasswordParams): Promise<ChangePasswordResult>;
  ResetPassword(request: ResetPasswordParams): Promise<ResetPasswordResult>;
  RequestAuthCode(request: RequestAuthCodeParams): Promise<RequestAuthCodeResult>;
  ExchangeAuthCode(request: ExchangeAuthCodeParams): Promise<ExchangeAuthCodeResult>;
  GetOIDCAuthURL(request: GetOIDCAuthURLParams): Promise<GetOIDCAuthURLResult>;
  OIDCLogin(request: OIDCLoginParams): Promise<OIDCLoginResult>;
}

export const AuthServiceName = "Auth";
export class AuthClientImpl implements Auth {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || AuthServiceName;
    this.rpc = rpc;
    this.Status = this.Status.bind(this);
    this.Signup = this.Signup.bind(this);
    this.Login = this.Login.bind(this);
    this.Logout = this.Logout.bind(this);
    this.ChangePassword = this.ChangePassword.bind(this);
    this.ResetPassword = this.ResetPassword.bind(this);
    this.RequestAuthCode = this.RequestAuthCode.bind(this);
    this.ExchangeAuthCode = this.ExchangeAuthCode.bind(this);
    this.GetOIDCAuthURL = this.GetOIDCAuthURL.bind(this);
    this.OIDCLogin = this.OIDCLogin.bind(this);
  }
  Status(request: StatusParams): Promise<StatusResult> {
    const data = StatusParams.encode(request).finish();
    const promise = this.rpc.request(this.service, "Status", data);
    return promise.then((data) => StatusResult.decode(new BinaryReader(data)));
  }

  Signup(request: SignupParams): Promise<SignupResult> {
    const data = SignupParams.encode(request).finish();
    const promise = this.rpc.request(this.service, "Signup", data);
    return promise.then((data) => SignupResult.decode(new BinaryReader(data)));
  }

  Login(request: LoginParams): Promise<LoginResult> {
    const data = LoginParams.encode(request).finish();
    const promise = this.rpc.request(this.service, "Login", data);
    return promise.then((data) => LoginResult.decode(new BinaryReader(data)));
  }

  Logout(request: LogoutParams): Promise<LogoutResult> {
    const data = LogoutParams.encode(request).finish();
    const promise = this.rpc.request(this.service, "Logout", data);
    return promise.then((data) => LogoutResult.decode(new BinaryReader(data)));
  }

  ChangePassword(request: ChangePasswordParams): Promise<ChangePasswordResult> {
    const data = ChangePasswordParams.encode(request).finish();
    const promise = this.rpc.request(this.service, "ChangePassword", data);
    return promise.then((data) => ChangePasswordResult.decode(new BinaryReader(data)));
  }

  ResetPassword(request: ResetPasswordParams): Promise<ResetPasswordResult> {
    const data = ResetPasswordParams.encode(request).finish();
    const promise = this.rpc.request(this.service, "ResetPassword", data);
    return promise.then((data) => ResetPasswordResult.decode(new BinaryReader(data)));
  }

  RequestAuthCode(request: RequestAuthCodeParams): Promise<RequestAuthCodeResult> {
    const data = RequestAuthCodeParams.encode(request).finish();
    const promise = this.rpc.request(this.service, "RequestAuthCode", data);
    return promise.then((data) => RequestAuthCodeResult.decode(new BinaryReader(data)));
  }

  ExchangeAuthCode(request: ExchangeAuthCodeParams): Promise<ExchangeAuthCodeResult> {
    const data = ExchangeAuthCodeParams.encode(request).finish();
    const promise = this.rpc.request(this.service, "ExchangeAuthCode", data);
    return promise.then((data) => ExchangeAuthCodeResult.decode(new BinaryReader(data)));
  }

  GetOIDCAuthURL(request: GetOIDCAuthURLParams): Promise<GetOIDCAuthURLResult> {
    const data = GetOIDCAuthURLParams.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetOIDCAuthURL", data);
    return promise.then((data) => GetOIDCAuthURLResult.decode(new BinaryReader(data)));
  }

  OIDCLogin(request: OIDCLoginParams): Promise<OIDCLoginResult> {
    const data = OIDCLoginParams.encode(request).finish();
    const promise = this.rpc.request(this.service, "OIDCLogin", data);
    return promise.then((data) => OIDCLoginResult.decode(new BinaryReader(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
